# Generated by Django 5.0.6 on 2024-08-11 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_accessories_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='description',
        ),
        migrations.RemoveField(
            model_name='store',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='store',
            name='img',
        ),
        migrations.RemoveField(
            model_name='store',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='store',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='store',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='unit',
            field=models.CharField(blank=True, choices=[('GB', 'Gigabytes'), ('TB', 'Terabytes')], max_length=2, null=True, verbose_name='Size unit'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='main.product'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Product size'),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
