# Generated by Django 5.0.6 on 2024-08-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_product_series_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='color_image',
        ),
    ]
