# Generated by Django 5.0.6 on 2024-08-12 13:00

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_product_detail_color_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color Code')),
                ('color_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.color'),
        ),
        migrations.AlterUniqueTogether(
            name='product_detail',
            unique_together={('product', 'color', 'series')},
        ),
    ]
