# Generated by Django 5.0.6 on 2024-08-12 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_color_product_alter_product_detail_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product_detail',
            unique_together={('product', 'size', 'series')},
        ),
        migrations.AlterField(
            model_name='color',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='main.product'),
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('product', 'color_code')},
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='color',
        ),
    ]
