# Generated by Django 5.0.6 on 2024-08-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_cart_accessory_cart_price_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
