# Generated by Django 5.0.6 on 2024-08-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_cart_accessory_remove_cart_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Product size'),
        ),
    ]
