# Generated by Django 5.0.6 on 2024-08-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_remove_product_size_remove_product_detail_price_and_more'),
    ]

    operations = [
    ]
