# Generated by Django 5.0.6 on 2024-08-14 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20240814_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='accessory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.accessories'),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.size'),
        ),
    ]
