# Generated by Django 5.0.6 on 2024-08-14 20:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_cart_accessory_cart_price_cart_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product', 'size')},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='accessory',
        ),
    ]
