# Generated by Django 5.0.6 on 2024-08-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_cart_unique_together_remove_cart_accessory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
    ]
