# Generated by Django 5.0.6 on 2024-08-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_product_description_battery_life_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='price',
        ),
    ]
