# Generated by Django 5.0.6 on 2024-08-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_size_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product360Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='360_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_360_images', to='main.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
