# Generated by Django 5.0.6 on 2024-08-25 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_product360image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product360image',
            name='image',
            field=models.ImageField(upload_to='360_views/'),
        ),
        migrations.AlterField(
            model_name='product360image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_360_views', to='main.product'),
        ),
    ]
